import time
import threading
import requests
import re
import login as login


class threadtester (threading.Thread):
    def __init__(self, galaxy, system , sid):
       threading.Thread.__init__(self)
       self.galaxy = galaxy
       self.system = system
       self.sid = sid
       
    def run(self):
        isBotschutz = True
        while isBotschutz:
            #print (f'Galaxy:{self.galaxy} und System:{self.system}')
            url =f'http://www.earthlost.de/galaxy.phtml?universe=3&galaxy={self.galaxy}&system={self.system}&sid={self.sid}'
            response = requests.get(url)
            #if botschutz.isBotSchutzOderNichtEingeloggt(response.text):
            #   print("welcherPlanetHatKeinenAuftrag")
             ##   self.sid = login.doLogin()
             #   continue
            isBotschutz = False
        planetenListe = re.findall('drawPlanet(.+?)\);',response.text)
        i=0
        for planet in planetenListe:
            planetAttribute = planet.split(',')         
           # print (f'Galaxy:{self.galaxy} und System:{self.system} und Planet {planetAttribute[0]}:{planetAttribute[1]}:{planetAttribute[2]}')
            try:
                if len(planetAttribute)!=16:
                    while len(planetAttribute) > 16:
                        planetAttribute.pop(4)
                
                if (re.search('""',planetAttribute[3]) and int(planetAttribute[7]) > 1) or (int(planetAttribute[11]) == 10 and int(planetAttribute[7]) > 1) :
                    freiOderGelb= 'gelb' if planetAttribute[11]==' 10' else 'frei'
                    print (f'{self.galaxy}:{self.system}:{i} - {planetAttribute[7]} Punkte - {freiOderGelb}')
            except:
                print (f'Fehler: {self.galaxy}:{self.system}')
            i=i+1

if __name__=="__main__":
    g = 1
    while g <= 25:
        y = 0
        while y <= 500:
            sid = login.doLogin()
            time.sleep(1)
            #print (sid)
            thread1 = threadtester(g,1+ y, sid)
            thread2 = threadtester(g,2+ y, sid)
            thread3 = threadtester(g,3+ y, sid)
            thread4 = threadtester(g,4+ y, sid)
            thread5 = threadtester(g,5+ y, sid)
            thread6 = threadtester(g,6+ y, sid)
            thread7 = threadtester(g,7+ y, sid)
            thread8 = threadtester(g,8+ y, sid)
            thread9 = threadtester(g,9+ y, sid)
            thread10 = threadtester(g,10+ y, sid)
            thread11 = threadtester(g,11+ y, sid)
            thread12 = threadtester(g,12+ y, sid)
            thread13 = threadtester(g,13+ y, sid)
            thread14 = threadtester(g,14+ y, sid)
            thread15 = threadtester(g,15+ y, sid)
            thread16 = threadtester(g,16+ y, sid)
            thread17 = threadtester(g,17+ y, sid)
            thread18 = threadtester(g,18+ y, sid)
            thread19 = threadtester(g,19+ y, sid)
            thread20 = threadtester(g,20+ y, sid)
            thread21 = threadtester(g,21+ y, sid)
            thread22 = threadtester(g,22+ y, sid)
            thread23 = threadtester(g,23+ y, sid)
            thread24 = threadtester(g,24+ y, sid)
            thread25 = threadtester(g,25+ y, sid)
            thread26 = threadtester(g,26+ y, sid)
            thread27 = threadtester(g,27+ y, sid)
            thread28 = threadtester(g,28+ y, sid)
            thread29 = threadtester(g,29+ y, sid)
            thread30 = threadtester(g,30+ y, sid)
            thread31 = threadtester(g,31+ y, sid)
            thread32 = threadtester(g,32+ y, sid)
            thread33 = threadtester(g,33+ y, sid)
            thread34 = threadtester(g,34+ y, sid)
            thread35 = threadtester(g,35+ y, sid)
            thread36 = threadtester(g,36+ y, sid)
            thread37 = threadtester(g,37+ y, sid)
            thread38 = threadtester(g,38+ y, sid)
            thread39 = threadtester(g,39+ y, sid)
            thread40 = threadtester(g,40+ y, sid)
            thread41 = threadtester(g,41+ y, sid)
            thread42 = threadtester(g,42+ y, sid)
            thread43 = threadtester(g,43+ y, sid)
            thread44 = threadtester(g,44+ y, sid)
            thread45 = threadtester(g,45+ y, sid)
            thread46 = threadtester(g,46+ y, sid)
            thread47 = threadtester(g,47+ y, sid)
            thread48 = threadtester(g,48+ y, sid)
            thread49 = threadtester(g,49+ y, sid)
            thread50 = threadtester(g,50+ y, sid)
            thread51 = threadtester(g,51+ y, sid)
            thread52 = threadtester(g,52+ y, sid)
            thread53 = threadtester(g,53+ y, sid)
            thread54 = threadtester(g,54+ y, sid)
            thread55 = threadtester(g,55+ y, sid)
            thread56 = threadtester(g,56+ y, sid)
            thread57 = threadtester(g,57+ y, sid)
            thread58 = threadtester(g,58+ y, sid)
            thread59 = threadtester(g,59+ y, sid)
            thread60 = threadtester(g,60+ y, sid)
            thread61 = threadtester(g,61+ y, sid)
            thread62 = threadtester(g,62+ y, sid)
            thread63 = threadtester(g,63+ y, sid)
            thread64 = threadtester(g,64+ y, sid)
            thread65 = threadtester(g,65+ y, sid)
            thread66 = threadtester(g,66+ y, sid)
            thread67 = threadtester(g,67+ y, sid)
            thread68 = threadtester(g,68+ y, sid)
            thread69 = threadtester(g,69+ y, sid)
            thread70 = threadtester(g,70+ y, sid)
            thread71 = threadtester(g,71+ y, sid)
            thread72 = threadtester(g,72+ y, sid)
            thread73 = threadtester(g,73+ y, sid)
            thread74 = threadtester(g,74+ y, sid)
            thread75 = threadtester(g,75+ y, sid)
            thread76 = threadtester(g,76+ y, sid)
            thread77 = threadtester(g,77+ y, sid)
            thread78 = threadtester(g,78+ y, sid)
            thread79 = threadtester(g,79+ y, sid)
            thread80 = threadtester(g,80+ y, sid)
            thread81 = threadtester(g,81+ y, sid)
            thread82 = threadtester(g,82+ y, sid)
            thread83 = threadtester(g,83+ y, sid)
            thread84 = threadtester(g,84+ y, sid)
            thread85 = threadtester(g,85+ y, sid)
            thread86 = threadtester(g,86+ y, sid)
            thread87 = threadtester(g,87+ y, sid)
            thread88 = threadtester(g,88+ y, sid)
            thread89 = threadtester(g,89+ y, sid)
            thread90 = threadtester(g,90+ y, sid)
            thread91 = threadtester(g,91+ y, sid)
            thread92 = threadtester(g,92+ y, sid)
            thread93 = threadtester(g,93+ y, sid)
            thread94 = threadtester(g,94+ y, sid)
            thread95 = threadtester(g,95+ y, sid)
            thread96 = threadtester(g,96+ y, sid)
            thread97 = threadtester(g,97+ y, sid)
            thread98 = threadtester(g,98+ y, sid)
            thread99 = threadtester(g,99+ y, sid)
            thread100 = threadtester(g,100+ y, sid)

            thread1.start()
            thread2.start()
            thread3.start()
            thread4.start()
            thread5.start()
            thread6.start()
            thread7.start()
            thread8.start()
            thread9.start()
            thread10.start()
            thread11.start()
            thread12.start()
            thread13.start()
            thread14.start()
            thread15.start()
            thread16.start()
            thread17.start()
            thread18.start()
            thread19.start()
            thread20.start()
            thread21.start()
            thread22.start()
            thread23.start()
            thread24.start()
            thread25.start()
            thread26.start()
            thread27.start()
            thread28.start()
            thread29.start()
            thread30.start()
            thread31.start()
            thread32.start()
            thread33.start()
            thread34.start()
            thread35.start()
            thread36.start()
            thread37.start()
            thread38.start()
            thread39.start()
            thread40.start()
            thread41.start()
            thread42.start()
            thread43.start()
            thread44.start()
            thread45.start()
            thread46.start()
            thread47.start()
            thread48.start()
            thread49.start()
            thread50.start()
            thread51.start()
            thread52.start()
            thread53.start()
            thread54.start()
            thread55.start()
            thread56.start()
            thread57.start()
            thread58.start()
            thread59.start()
            thread60.start()
            thread61.start()
            thread62.start()
            thread63.start()
            thread64.start()
            thread65.start()
            thread66.start()
            thread67.start()
            thread68.start()
            thread69.start()
            thread70.start()
            thread71.start()
            thread72.start()
            thread73.start()
            thread74.start()
            thread75.start()
            thread76.start()
            thread77.start()
            thread78.start()
            thread79.start()
            thread80.start()
            thread81.start()
            thread82.start()
            thread83.start()
            thread84.start()
            thread85.start()
            thread86.start()
            thread87.start()
            thread88.start()
            thread89.start()
            thread90.start()
            thread91.start()
            thread92.start()
            thread93.start()
            thread94.start()
            thread95.start()
            thread96.start()
            thread97.start()
            thread98.start()
            thread99.start()
            thread100.start()
            #print(f'Bis System:{y} gescannt')
            time.sleep(1)
            y= y+100
        g = g +1




